allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - eslint@10.8.0
  - '@iconify-json/lucide@1.2.123'
  - tsx@4.23.12
